### ISSUE TITLE
package.json not in same directory as serverless.yml

### ISSUE THREAD

**Issue by davetownsend** [iopipe/serverless-plugin-iopipe#34]
My project has multiple `serverless.yml` files (services) with a `package.json` in the root. `sls deploy` fails with `ENOENT: no such file or directory` because it can't  find the `package.json` file. 

I've set the following trying to bypass but not helping:

```yml
custom:
  iopipeNoVerify: true
  iopipeNoUpgrade: true
```
Any way to specify `package.json` location or get around the error?
