### ISSUE TITLE
Lambda functions triggered by kinesis stream fail with timeout 

### ISSUE THREAD

**Issue by mskutin** [iopipe/serverless-plugin-iopipe#91]
**Description**
Plugin doesn't work when lambda function is event sourced with kinesis stream, causing function to always fail by timeout. Function is executed successfully, but the lambda is kept alive until reached specified timeout.

**Steps to reproduce the issue:**
```yaml
# serverless.yml

frameworkVersion: ">=1.0.0 <2.0.0"

service: myservice
custom:
  iopipeNoVerify: false
  iopipeNoStats: true
  
provider:
  name: aws
  cfLogs: true
  runtime: nodejs8.10
  tracing: true
  environment:
    IOPIPE_TOKEN: ${file(config/${self:custom.stage}.yml):IOPIPE_TOKEN}
    IOPIPE_LOGGER_ENABLED: true

functions:
  triggerEvent:
    handler: ${self:custom.servicesHandlerBasePath}/triggerEvent.handler
    events:
      - stream:
          type: kinesis
          arn: "arn:aws:kinesis:#{AWS::Region}:#{AWS::AccountId}:stream/kinesis-${self:custom.stage}"
          batchSize: 5
          startingPosition: TRIM_HORIZON
          enabled: true
```

```javascript
#handler
let triggerEvent = (event, context, callback) => {
    event.Records.forEach((record) => {
        const payload = JSON.parse(Buffer.from(record.kinesis.data, 'base64').toString('ascii'))
        console.log('Kinesis record', payload)
    })
}
module.exports.handler = triggerEvent;
```

```javascript
#iopipe_handler

const iopipe = require('@iopipe/iopipe')({"installMethod":"serverless-plugin-iopipe@1.6.2","plugins":[]});

let handler, handlerError;
// The following is an automatically generated require statement by the plugin,
// aimed to provide syntax/type errors to the IOpipe service.
// The original file is imported as text with capitalized tokens replaced.
try {
  handler = require('../src/services/triggerEvent');
} catch (err) {
  handlerError = err;
}

exports['triggerEvent'] = function attempttriggerEvent(event, context, callback) {
  try {
    return iopipe((evt, ctx, cb) => {
      if (handlerError) {
        return cb(handlerError);
      }
      return handler.handler(evt, ctx, cb);
    })(event, context, callback);
  } catch (err) {
    throw err;
  }
};
```
**Describe the results you received:**
- Function is failing by timeout, no matter what timeout is specified
- Function is not shown in iopipe dashboard

**Describe the results you expected:**
Expected to see working plugin.

**Application and library versions**
```javascript
"dependencies": {
        "@iopipe/iopipe": "^1.9.0",
        "aws-sdk": "^2.224.1",
        "body-parser": "^1.18.2",
        "express": "^4.16.3",
        "serverless": "^1.26.1",
        "serverless-http": "^1.5.3"
    },
    "devDependencies": {
        "serverless-dynamodb-client": "0.0.2",
        "serverless-graph": "^0.3.2",
        "serverless-offline": "^3.18.0",
        "serverless-plugin-diff": "^1.3.0",
        "serverless-plugin-iopipe": "^1.6.2",
        "serverless-plugin-tracing": "^2.0.0",
        "serverless-pseudo-parameters": "^1.6.0"
    }
```

**Additional information you deem important (e.g. issue happens only occasionally):**
Disabling iopipe logging and\or tracing doesn't do any effect.

**Comment by kolanos** [comment]
@mskutin Can you enable `debug` mode and provide any relevant logs? That will give us an idea what it's timing out on.

Edit: My initial suggestion doesn't make sense after looking at the generated iopipe module more closely.

**Comment by mskutin** [comment]
@kolanos is there any progress or plans for the matter?

**Comment by kolanos** [comment]
@mskutin Did you provide debug logs via some other channel? Sorry, didn't see those if you did. We use Kinesis streams with this library heavily and have not had any timeout issues. Have you tried different options with your event trigger? You have:


```yaml
    events:
      - stream:
          type: kinesis
          arn: "arn:aws:kinesis:#{AWS::Region}:#{AWS::AccountId}:stream/kinesis-${self:custom.stage}"
          batchSize: 5
          startingPosition: TRIM_HORIZON
          enabled: true
```

Ours looks like this:

```yaml
    events:
      - stream:
          arn: ${self.custom.arn} 
          batchSize: 1000
          startingPosition: LATEST
          enabled: true
```

Have you tried different `batchSize` and `startingPosition` options? Also, we don't include a `type` with the stream trigger.

Try disabling the IOpipe logger as well. If your function can't reach our signer, it could result in a timeout.
